name: Run

on:
  workflow_dispatch:
    inputs:
      args:
        description: "Arguments to pass to WikiExplorer.py"
        default: ""


run-name: "Run: ${{ github.event.inputs.args }}"

jobs:
  running_execution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Cache Python packages
        uses: actions/cache@v4
        with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - run: pip install -r requirements.txt
      - run: python -m spacy download en_core_web_lg
      - run: python WikiExplorer.py ${{ github.event.inputs.args }}
